version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs/pglogs:/var/log/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  web:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./logs/applogs:/app/logs

volumes:
  pgdata:
