version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pglogs:/var/lib/postgresql/data/logs
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh

  web:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./logs/applogs:/app/logs

volumes:
  pgdata:
