# Test your FastAPI endpoints

GET http://127.0.0.1:8000/posts
Accept: application/json

###

GET http://127.0.0.1:8000/posts
Accept: application/json

{
    "title": "Test title",
    "content": "text"
}